# Generated by Django 5.2.3 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('member', 'Member')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
