# Generated by Django 5.2.3 on 2025-07-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_favoritebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
