# Generated by Django 5.2.3 on 2025-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_member_delete_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual')], max_length=15),
        ),
    ]
