# Generated by Django 5.2.3 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_member_qr_code_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_verified_by_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
